### ISSUE TITLE
[Bug]: Cannot unmarshal string - workflow template fail

### ISSUE THREAD

**Issue by goranbs** [DataCloud-project/SIM-PIPE#122]
### Current behavior

No error message is displayed when this error occurs.

### Expected behavior

Dismplay an error message describing why this happens.

### Steps to reproduce

Insert the following workflow template ("sleep 5; " has been added to the example workflow template "artifact-passing.yaml"):

# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 5; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["sleep5; cat /tmp/message"]

### Environment

- SIM-PIPE version:
- Platform/OS:
- Browser:
- Other:

### Logs

```shell
Uncaught (in promise) Error: json: cannot unmarshal string into Go struct field Container.template.spec.templates.container.command of type []string: {"response":{"errors":[{"message":"json: cannot unmarshal string into Go struct field Container.template.spec.templates.container.command of type []string","locations":[{"line":3,"column":3}],"path":["createWorkflowTemplate"],"extensions":{"code":"INVALID_ARGO_WORKFLOW_TEMPLATE_ERROR","stacktrace":["GraphQLError: json: cannot unmarshal string into Go struct field Container.template.spec.templates.container.command of type []string","    at new InvalidArgoWorkflowTemplateError (file:///app/server/apollo-errors.js:51:9)","    at createWorkflowTemplate (file:///app/argo/workflow-template.js:47:19)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Object.createWorkflowTemplate (file:///app/server/resolvers.js:169:20)"]}}],"data":null,"status":200,"headers":{"map":{"cache-control":"no-store","content-length":"778","content-type":"application/json; charset=utf-8"}}},"request":{"query":"\n\tmutation Mutation($input: CreateWorkflowTemplateInput!) {\n\t\tcreateWorkflowTemplate(input: $input) {\n\t\t\tname\n\t\t\tproject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n","variables":{"input":{"argoWorkflowTemplate":{"apiVersion":"argoproj.io/v1alpha1","kind":"Workflow","metadata":{"generateName":"artifact-passing-"},"spec":{"entrypoint":"artifact-example","templates":[{"name":"artifact-example","steps":[[{"name":"generate-artifact","template":"whalesay"}],[{"name":"consume-artifact","template":"print-message","arguments":{"artifacts":[{"name":"message","from":"{{steps.generate-artifact.outputs.artifacts.hello-art}}"}]}}]]},{"name":"whalesay","container":{"image":"docker/whalesay:latest","command":["sh","-c"],"args":["sleep 5; cowsay hello world | tee /tmp/hello_world.txt"]},"outputs":{"artifacts":[{"name":"hello-art","path":"/tmp/hello_world.txt"}]}},{"name":"print-message","inputs":{"artifacts":[{"name":"message","path":"/tmp/message"}]},"container":{"image":"alpine:latest","command":"sh, -c]","args":["sleep 5; cat /tmp/message"]}}]}},"name":"artifact-passing-1","projectId":"artifact-passing-1"}}}}
    at makeRequest (index.ts:426:11)
    at async requestGraphQLClient (graphqlUtils.ts:20:9)
    at async HTMLButtonElement.onCreateProjectSubmit (modal-submit-new-project.svelte:58:53)
```

**Comment by goranbs** [comment]
TODO: Try to create a workflow template with a obvious mistake in stead. The above workflow template seem too work nicely after all..
